spring.application.name=restaurant-service
server.port=8082

eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.datasource.url=jdbc:postgresql://localhost:5432/food_restaurant
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=food_user
spring.datasource.password=food01
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

