spring.application.name=auth-service
server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/food_auth
spring.datasource.username=food_user
spring.datasource.password=food01

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=ed8e3bd84a15633d1d807b9d661f037f2e5ca3412c8748e4b3220e4ae3b36c53
jwt.expiration=3600000